name: SSH

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /home/mbougarne/
            git clone https://github.com/mbougarne/mbougarne.me.git gatsby-site
            cd gatsby-site
            npm install
            npm run build
            mv -v ./public/* ../public_html/
            echo "DONE!"

